### ISSUE TITLE
'&' filter is not working

### ISSUE THREAD

**Issue by mcauto** [miki725/alchemy-mock#18]
I love this library! It's useful!

I want to contribute this project.

but I'm not good at understand sqlalchemy and this library

I have below problem.

could you help me?

```python
"""
    in db session
    [A(id = 1, user_id="tester")]
    [B(id = 1, a_id = 1)]
"""
s = UnifiedAlchemyMagicMock()
for a in A_list:
    s.add(a)
for b in B_list:
    s.add(b)

filter = (A.id == B.a_id) & (A.user_id == 'tester')
result = session.query(B).filter(filter).all() 
(pdb) result 
[B(id=1, a_id=1)] # good!

filter = (A.id == B.a_id) & (A.user_id == 'whoareyou')
result = session.query(B).filter(filter).all() 
(pdb) result
[B(id=1, a_id=1)] # ?? filter is not working
```

**Comment by miki725** [comment]
thanks for the kind words.

Unfortunately what you are attempting to do currently is not possible. From readme:

https://github.com/miki725/alchemy-mock/blob/82f4e1c2e6f3058e678f39f533464220a9d0f3c0/README.rst#L108-L125

Specifically:

https://github.com/miki725/alchemy-mock/blob/82f4e1c2e6f3058e678f39f533464220a9d0f3c0/README.rst#L121-L122

Traditionally when filtering objects SQLAlchemy will send the query back to the DB and let the DB do the filtering for it. Since when using this library DB is mocked out, filtering cannot be automatically applied. Only exception is `.get()` since that gets the items from identity map which bypasses DB so this library emulates that.

What you can do is manually add data to `UnifiedAlchemyMagicMock` with filters applied which should work as expected:

```python
m = UnifiedAlchemyMagicMock(data=[
  (
    [mock.call.query(A),
     mock.call.filter((A.id == B.a_id) & (A.user_id == 'whoareyou'))],
    [<models you would like to return for this filter>]
  ),
])
```

there are couple of examples like that in readme

**Comment by mcauto** [comment]
I understand! thank you
